version: 2.1

orbs:
  ghpr: narrativescience/ghpr@1.0.3

executors:
  default:
    working_directory: ~/workspace
      #environment:
      #  CYPRESS_CACHE_FOLDER: '~/.cache/Cypress'
    docker:
      - image: circleci/node:11.15.0

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache
  unit_test:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: unit test
          command: npx jest --ci --runInBand --reporters=default --reporters=jest-junit --coverage
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
    ` - ghpr/post-pr-comment
          comment: Hello
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./coverage

workflows:
  demo:
    jobs:
      - setup
      - unit_test:
          requires:
            - setup
